config/routes.rb
Rails.application.routes.draw do
  resources :lgtm_images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lgtm_image.rb
class LgtmImage < ApplicationRecord
  validates :url, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lgtm_images_controller.rb
class LgtmImagesController < ApplicationController
  before_action :set_lgtm_image, only: [:show, :edit, :update, :destroy]

  # GET /lgtm_images
  # GET /lgtm_images.json
  def index
    @lgtm_images = LgtmImage.all
  end

  # GET /lgtm_images/1
  # GET /lgtm_images/1.json
  def show
  end

  # GET /lgtm_images/new
  def new
    @lgtm_image = LgtmImage.new
  end

  # GET /lgtm_images/1/edit
  def edit
  end

  # POST /lgtm_images
  # POST /lgtm_images.json
  def create
    @lgtm_image = LgtmImage.new(lgtm_image_params)

    respond_to do |format|
      if @lgtm_image.save
        format.html { redirect_to @lgtm_image, notice: 'Lgtm image was successfully created.' }
        format.json { render :show, status: :created, location: @lgtm_image }
      else
        format.html { render :new }
        format.json { render json: @lgtm_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lgtm_images/1
  # PATCH/PUT /lgtm_images/1.json
  def update
    respond_to do |format|
      if @lgtm_image.update(lgtm_image_params)
        format.html { redirect_to @lgtm_image, notice: 'Lgtm image was successfully updated.' }
        format.json { render :show, status: :ok, location: @lgtm_image }
      else
        format.html { render :edit }
        format.json { render json: @lgtm_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lgtm_images/1
  # DELETE /lgtm_images/1.json
  def destroy
    @lgtm_image.destroy
    respond_to do |format|
      format.html { redirect_to lgtm_images_url, notice: 'Lgtm image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lgtm_image
      @lgtm_image = LgtmImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lgtm_image_params
      params.require(:lgtm_image).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lgtm_images_helper.rb
module LgtmImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeLgtm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lgtm_images/_form.html.erb
<%= form_with(model: lgtm_image, local: true) do |form| %>
  <% if lgtm_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lgtm_image.errors.count, "error") %> prohibited this lgtm_image from being saved:</h2>

      <ul>
      <% lgtm_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :lgtm_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lgtm_images/edit.html.erb
<h1>Editing Lgtm Image</h1>

<%= render 'form', lgtm_image: @lgtm_image %>

<%= link_to 'Show', @lgtm_image %> |
<%= link_to 'Back', lgtm_images_path %>

app/views/lgtm_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lgtm Images</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lgtm_images.each do |lgtm_image| %>
      <tr>
        <td><%= image_tag lgtm_image.url %></td>
        <td><%= link_to 'Destroy', lgtm_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lgtm Image', new_lgtm_image_path %>

app/views/lgtm_images/new.html.erb
<h1>New Lgtm Image</h1>

<%= render 'form', lgtm_image: @lgtm_image %>

<%= link_to 'Back', lgtm_images_path %>

app/views/lgtm_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @lgtm_image.url %>
</p>

<%= link_to 'Edit', edit_lgtm_image_path(@lgtm_image) %> |
<%= link_to 'Back', lgtm_images_path %>